"""add_face_crop_data

Revision ID: 492d3537f49b
Revises: 0003
Create Date: 2026-05-28 15:21:50.234070

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '492d3537f49b'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_thumbnails')
    op.alter_column('faces', 'file_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last time face data was written to the image file XMP',
               existing_nullable=True)
    op.drop_index(op.f('ix_faces_embedding_notnull'), table_name='faces', postgresql_where='(embedding IS NOT NULL)')
    op.alter_column('photos', 'meta_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last time photo metadata was written to the image file XMP',
               existing_nullable=True)
    op.alter_column('photos', 'file_modified_at_sync',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='file mtime when we last synced FROM the file into DB',
               existing_nullable=True)
    op.drop_index(op.f('ix_tags_path_gist'), table_name='tags', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tags_path_gist'), 'tags', ['path'], unique=False, postgresql_using='gist')
    op.alter_column('photos', 'file_modified_at_sync',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='file mtime when we last synced FROM the file into DB',
               existing_nullable=True)
    op.alter_column('photos', 'meta_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time photo metadata was written to the image file XMP',
               existing_nullable=True)
    op.create_index(op.f('ix_faces_embedding_notnull'), 'faces', ['photo_id'], unique=False, postgresql_where='(embedding IS NOT NULL)')
    op.alter_column('faces', 'file_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time face data was written to the image file XMP',
               existing_nullable=True)
    op.create_table('photo_thumbnails',
    sa.Column('photo_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('photo_thumbnails_photo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'size', name=op.f('photo_thumbnails_pkey'))
    )
    # ### end Alembic commands ###
